### ISSUE TITLE
css 스타일링 수정

### ISSUE THREAD

**Issue by moooooonchild** [efub-ecyce/Ecyce-Front#20]
## Description
- css 어색한 부분 수정

## To-Do
- [x] 헤더 위치 확인
- [x] 네비바 위치 확인
- [x] 스크롤 이상한 부분 있는지 확인

## ETC
