### ISSUE TITLE
메인 페이지 API 연결

### ISSUE THREAD

**Issue by billy0904** [efub-ecyce/Ecyce-Front#42]
## Description
- 메인 페이지 api 연결
  - 상품 카테고리 api 연결
- 상품 상세 페이지 api 연결

## To-Do
- [x] 전체 상품 조회
- [x] 단일 상품 조회
- [x] 카테고리별 상품 조회

## ETC
